### ISSUE TITLE
Form.clear broken

### ISSUE THREAD

**Issue by hstaudacher** [ui4j/ui4j#43]
It seems that the last commits broke `Form.clear`. My tests are red now and they were green before the last pull.

**Comment by ui4j** [comment]
Fixed. Additionality latest implementation of the `Form.clear` method clears the textarea elements.

**Comment by hstaudacher** [comment]
Thanks, but now the build fails :)

**Comment by ui4j** [comment]
Yes, previous builds are broken but the latest one is finished successfully.

https://drone.io/github.com/ui4j/ui4j/95

**Comment by hstaudacher** [comment]
It's not fixed for me. This is the html form:

```html
    <form id="form">
      <input type="text" name="a" />
      <input type="text" name="b" />
      <input type="submit" name="submit" value="Submit" />
    </form>
```

This is the test case (maybe you need to adapt to compile against ui4j):

```java
  @Test
  public void testClearsForm() {
    form.getElement().getDocument().query( "input[name='a']" ).get().setValue( "foo" );
    form.getElement().getDocument().query( "input[name='b']" ).get().setValue( "bar" );

    form.clear();

    assertThat( form.getElement().getDocument().query( "input[name='a']" ).get().getValue().isPresent() ).isFalse();
    assertThat( form.getElement().getDocument().query( "input[name='b']" ).get().getValue().isPresent() ).isFalse();
  }
```

**Comment by ui4j** [comment]
Fixed now.
